// <auto-generated />
using GeekShopping.ProductApi.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductApi.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20231114201926_corrective_migration")]
    partial class corrective_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductApi.Model.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("ImmageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("immage_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            id = 2L,
                            CategoryName = "T-Shirt",
                            Description = "Description",
                            ImmageUrl = "https://github.com/FelipePassos09/GeekStore-microservices/blob/main/ShoppingImages/5_100_gamer.jpg",
                            Name = "Camiseta Gamer",
                            Price = 69.9m
                        },
                        new
                        {
                            id = 3L,
                            CategoryName = "T-Shirt",
                            Description = "Description",
                            ImmageUrl = "https://github.com/FelipePassos09/GeekStore-microservices/blob/main/ShoppingImages/6_spacex.jpg",
                            Name = "Camiseta SpaceX",
                            Price = 69.9m
                        },
                        new
                        {
                            id = 4L,
                            CategoryName = "Action-Figure",
                            Description = "Description",
                            ImmageUrl = "https://github.com/FelipePassos09/GeekStore-microservices/blob/main/ShoppingImages/4_storm_tropper.jpg",
                            Name = "Storm Trooper",
                            Price = 29.9m
                        },
                        new
                        {
                            id = 5L,
                            CategoryName = "Toy",
                            Description = "Description",
                            ImmageUrl = "https://github.com/FelipePassos09/GeekStore-microservices/blob/main/ShoppingImages/3_vader.jpg",
                            Name = "Darth Vader Helm",
                            Price = 98.5m
                        },
                        new
                        {
                            id = 6L,
                            CategoryName = "T-Shirt",
                            Description = "Description",
                            ImmageUrl = "https://github.com/FelipePassos09/GeekStore-microservices/blob/main/ShoppingImages/7_coffee.jpg",
                            Name = "camiseta Feminina Drink Coffe ",
                            Price = 69.9m
                        },
                        new
                        {
                            id = 7L,
                            CategoryName = "Sweatshirt",
                            Description = "Description",
                            ImmageUrl = "https://github.com/FelipePassos09/GeekStore-microservices/blob/main/ShoppingImages/8_moletom_cobra_kay.jpg",
                            Name = "Moletom Cobra-Kai",
                            Price = 89.9m
                        },
                        new
                        {
                            id = 8L,
                            CategoryName = "Book",
                            Description = "Description",
                            ImmageUrl = "https://github.com/FelipePassos09/GeekStore-microservices/blob/main/ShoppingImages/9_neil.jpg",
                            Name = "Livro Star Talk - Neil DeFrasse Tyson",
                            Price = 49.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
